version: '3.4'

services:

  mongodb:
   image: mongo:4.4-bionic
   ports:
   - 27017:27017

  inventory-api:
   image: ${DOCKER_REGISTRY-}inventory.api
   build:
    context: .
    dockerfile: CarsUnlimited.InventoryAPI/Dockerfile
   ports:
    - 5010:80
   environment:
   - ASPNETCORE_ENVIRONMENT=Development
   - InventoryDatabaseSettings__ConnectionString=mongodb://mongodb:27017
   depends_on:
    - mongodb