version: '3.7'

services:

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"

  cartdb:
   image: redis:6.2-alpine
   ports:
   - 6379:6379

  inventorydb:
   image: mongo:4.4-bionic
   ports:
   - 27017:27017