version: '3.7'

services:

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"

  rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: rabbitmq
      volumes:
          - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
          - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
          - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
      environment:
          RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
          RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
          RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      ports:
          - 5672:5672
          - 15672:15672

  cartdb:
   image: redis:6.2-alpine
   ports:
   - 6379:6379

  inventorydb:
   image: mongo:4.4-bionic
   ports:
   - 27017:27017

  inventory-api:
   image: ${DOCKER_REGISTRY-}inventory.api
   build:
    context: .
    dockerfile: CarsUnlimited.InventoryAPI/Dockerfile
   ports:
    - 5010:80
   environment:
   - ASPNETCORE_ENVIRONMENT=Development
   - InventoryDatabaseSettings__ConnectionString=mongodb://inventorydb:27017
   - TracingConfiguration__JaegerEndpoint__Host=jaeger
   - TracingConfiguration__JaegerEndpoint__Port=6831
   depends_on:
    - inventorydb    

  cart-api:
   image: ${DOCKER_REGISTRY-}cart.api
   build:
    context: .
    dockerfile: CarsUnlimited.CartAPI/Dockerfile
   ports:
    - 5020:80
   environment:
   - ASPNETCORE_ENVIRONMENT=Development
   - Redis__Password=""
   - RedisSettings__Ssl=false
   - RedisSettings__Host=cartdb
   - RedisSettings__Port=6379
   - TracingConfiguration__JaegerEndpoint__Host=jaeger
   - TracingConfiguration__JaegerEndpoint__Port=6831
   depends_on:
    - cartdb