version: '3.8'

services:

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"

  rabbitmq:
    image: 'docker.io/bitnami/rabbitmq:3.8-debian-10'
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/bitnami'

  cartdb:
   image: redis:6.2-alpine
   ports:
   - 6379:6379

  inventorydb:
   image: mongo:4.4-bionic
   ports:
   - 27017:27017

  kongdb:
    image: docker.io/bitnami/postgresql:11-debian-10
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=kong
      - POSTGRESQL_PASSWORD=bitnami
      - POSTGRESQL_DATABASE=kong
  kong:
    image: docker.io/bitnami/kong:2-debian-10
    ports:
      - 8000:8000
      - 8443:8443
    environment:
      - KONG_MIGRATE=yes
      - KONG_PG_HOST=kongdb
      - KONG_PG_PASSWORD=bitnami

  konga:
      image: pantsel/konga
      environment:
        TOKEN_SECRET: some-secret-token
        DB_ADAPTER: postgres
        DB_HOST: kongdb
        DB_PORT: 8000
        DB_DATABASE: kong
        DB_USER: kong
        DB_PASSWORD: bitnami
        NODE_ENV: production
        KONGA_HOOK_TIMEOUT: 10000
      restart: on-failure
      ports:
      - 9000:1337
      depends_on:
      - kongdb

  inventoryapi:
   image: ${DOCKER_REGISTRY-}inventory.api
   build:
    context: .
    dockerfile: CarsUnlimited.InventoryAPI/Dockerfile
   ports:
    - 5010:80
   environment:
   - ASPNETCORE_ENVIRONMENT=Development
   - InventoryDatabaseSettings__ConnectionString=mongodb://inventorydb:27017
   - TracingConfiguration__JaegerEndpoint__Host=jaeger
   - TracingConfiguration__JaegerEndpoint__Port=6831
   - InventoryApiKey=THIS_IS_MY_KEY
   depends_on:
    - inventorydb    

  inventoryworker:
   image: ${DOCKER_REGISTRY-}inventory.worker
   build:
    context: .
    dockerfile: CarsUnlimited.InventoryWorker/Dockerfile
   environment:
   - ASPNETCORE_ENVIRONMENT=Development
   - ServiceBusConfiguration__HostName=rabbitmq
   - ServiceBusConfiguration__UserName=user
   - ServiceBusConfiguration__Password=user
   - InventoryApiKey=THIS_IS_MY_KEY
   - InventoryApiUrl=http://inventoryapi/api/Inventory/
   depends_on:
    - inventorydb
    - rabbitmq
    - inventoryapi

  cartapi:
   image: ${DOCKER_REGISTRY-}cart.api
   build:
    context: .
    dockerfile: CarsUnlimited.CartAPI/Dockerfile
   ports:
    - 5020:80
   environment:
   - ASPNETCORE_ENVIRONMENT=Development
   - Redis__Password=""
   - RedisSettings__Ssl=false
   - RedisSettings__Host=cartdb
   - RedisSettings__Port=6379
   - TracingConfiguration__JaegerEndpoint__Host=jaeger
   - TracingConfiguration__JaegerEndpoint__Port=6831
   - ServiceBusConfiguration__HostName=rabbitmq
   - ServiceBusConfiguration__UserName=user
   - ServiceBusConfiguration__Password=user
   - CartApiKey=THIS_IS_MY_KEY
   depends_on:
    - cartdb
    - rabbitmq


  cartworker:
   image: ${DOCKER_REGISTRY-}cart.worker
   build:
    context: .
    dockerfile: CarsUnlimited.CartWorker/Dockerfile
   environment:
   - ASPNETCORE_ENVIRONMENT=Development
   - ServiceBusConfiguration__HostName=rabbitmq
   - ServiceBusConfiguration__UserName=user
   - ServiceBusConfiguration__Password=user
   - CartApiKey=THIS_IS_MY_KEY
   - CartApiUrl=http://cartapi/api/Cart/
   depends_on:
    - cartdb
    - rabbitmq
    - cartapi

  purchaseapi:
   image: ${DOCKER_REGISTRY-}purchase.api
   build:
    context: CarsUnlimited-Purchase-API
    dockerfile: Dockerfile
   environment:
    - SERVICE_BUS_CONNECTION_STRING=amqp://user:user@rabbitmq:5672/
   ports:
    - 5030:8080
   depends_on:
    - rabbitmq

volumes:
  rabbitmq_data:
    driver: local
  postgresql_data:
    driver: local