# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
          
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: ''
        run: gcloud iam service-accounts add-iam-policy-binding deployment-sa@pocs-352009.iam.gserviceaccount.com --member="serviceAccount:deployment-sa@pocs-352009.iam.gserviceaccount.com" --role="roles/iam.serviceAccountTokenCreator"
      
      - name: 'Create key'
        run: gcloud iam service-accounts keys create key-file.json --iam-account deployment-sa@pocs-352009.iam.gserviceaccount.com

      - name: 'Activate Service Account'
        run: gcloud auth activate-service-account deployment-sa@pocs-352009.iam.gserviceaccount.com --key-file=key-file.json
      
      - name: 'Create bucket for tfstate file' 
        run: gsutil -i "deployment-sa@pocs-352009.iam.gserviceaccount.com" mb gs://tfstate-bucket