# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Secret File
        uses: ttd2089/secret-file-action@1.0.0
        id: gc-key-file
        with:
          secret: '${{ secrets.GOOGLE_CREDENTIALS }}'


      - name: 'Activate Service Account'
        run: gcloud auth activate-service-account --key-file ${{ steps.gc-key-file.outputs.file }}

      - name: 'Create bucket for tfstate file'
        run: gsutil mb -p pocs-352009 gs://tfstate_bucket